ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS mac VARCHAR(32),
    ADD COLUMN IF NOT EXISTS note TEXT,
    ADD COLUMN IF NOT EXISTS username VARCHAR(100),
    ADD COLUMN IF NOT EXISTS password VARCHAR(255),
    ADD COLUMN IF NOT EXISTS template_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS dns_domain_id VARCHAR(100);
